Rails_Project/book_shelf/config/routes.rb
# nodoc
Rails.application.routes.draw do
  # get 'password_resets/new'

  # get 'password_resets/edit'

  # get 'password_reset/new'

  # get 'password_reset/edit'

  # get 'resumes/index'
  # get 'resumes/new'
  # get 'password_resets/new'

  # get 'password_resets/edit'

  # get 'password_reset/new'

  # get 'password_reset/edit'

  # get 'resumes/create'
  # get 'resumes/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "users" => 'users#index'
  # get "users/new" => 'users#new'
  # get "users/:id" => 'users#show'
  # get "users/:id/edit" => 'users#edit'
  # post "users" => 'users#create'
  # put "users/:id" => 'users#update'
  # delete "users/:id" => 'users#destroy'
# 	collection do 
# 		get 'most_like'
# 	end
# 	resources :comments do
# 		resources :users
# 	end
# end
# resources :post do
#   collection do 
#     get 'most_like'
#   end
#   member do
#     get 'most_comment'
#   end
#   # resources :comments do
#   #   # resources :users
#   # end
# end

get "books/items"
get "books/search_book"
get "books/search"
get  '/register',  to: 'users#new'
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'
get '/signup' => 'users#new'
# get "login"

# resources :sessions, only: [:create, :new, :destroy]

root "books#items"
resources :users
resources :orders
resources :carts
resources :books
resources :account_activations, only: [:edit]
resources :password_resets, only: [:create, :new, :update, :edit]
end

Rails_Project/book_shelf/app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id     :integer          not null, primary key
#  name   :string(255)
#  author :string(255)
#  title  :string(255)
#  isn    :string(255)
#
# nodoc:
class Book < ApplicationRecord
  validates :name, presence: true, length: { minimum: 5 }
  # mount_uploader :image, ImageUploader

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      scoped
    end
  end

  scope :author_search, ->(author) { where(['author LIKE ?', "%#{author}%"]) }
  scope :search_author, lambda { |author_name|
    joins(:order).where('books.author like :authorname', authorname: author_name)
  }
  has_many :orders
  has_many :carts, through: :orders
  has_many :comments
end

Rails_Project/book_shelf/app/controllers/books_controller.rb
# :nodoc:
class BooksController < ApplicationController
  layout 'application'
  before_action :paging, only: %i[items index]

  def paging
    @allpage = Book.all.count / 12
    @allpage = 1 if @allpage.zero?
    @page = params[:page].to_i
    @page = 1 if @page <= 0
    @page = @allpage if @page > @allpage
    @books = Book.all.limit(12).offset((@page - 1) * 12)
  end

  def items
    # items method
  end

  def search_book
    # search book
  end

  def search
    # binding.pry
    bookname = params[:search_value]
    @books = Book.search(bookname)
    # binding.pry
    # binding.pry
    # # @books = Book.joins(:orders).author_search(params[:search_value])
    # authorname = params[:search_value]
    # @book = Book.all.joins(:orders).where('books.author like
    # :authorname', authorname: authorname)
  end

  def index
    # index method
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render 'new'
    end
  end

  def destroy
    Book.find(params[:id]).destroy
    redirect_to books_path
    # binding.pry
  end

  def update
    @book = Book.find(params[:id])
    if @book.update_attributes(book_params)
      # binding.pry
      redirect_to @book
      # Handle a successful update.
    else
      render 'edit'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def show
    @book = Book.find(params[:id])
    # @books = Book.find(params[:id] )
    # @books.destroy
  end

  def book_params
    params.require(:book).permit(:name, :author, :title, :isn)
  end
end

Rails_Project/book_shelf/app/helpers/books_helper.rb
# nodoc
module BooksHelper
end

Rails_Project/book_shelf/app/views/books/_book.html.erb
<tr>
	<td><%= book.name %></td>
	<td><%= book.author %></td>
	<td><%= book.title %></td>
	<td><%= book.isn %></td>

	<td><%= link_to "edit", edit_book_path(book) %>/
	<%= link_to "delete",book,  :method => 'delete' , data: {confirm: "are you sure that you want to delete book#{book.name}?"} %>/
	<%= link_to "show", book_path(book) %></td>
</tr>

Rails_Project/book_shelf/app/views/books/_form.html.erb
<p><%= link_to 'All Books', books_path%></p>

<%= form_for (@book), html: {multipart: true}  do |f| %>
            <% #binding.pry %>
            <%  if  @book.errors.any?  %>
                <div  id="error_explanation">
                    <h2>
                        <%= pluralize(@book.errors.count,  "error")  %>  prohibited
                        this  article from  being saved:
                    </h2>
                    <div class="alert alert-error">
                        <ul>
                        <%  @book.errors.full_messages.each  do  |msg| %>
                            <li><%= msg %></li>
                        <%  end %>
                    </ul>
                    </div>
                  </div>
            <%  end %>

            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %><br>

            <%= f.label :author %>
            <%= f.text_field :author, class: 'form-control' %><br>

            <%= f.label :title %>
            <%= f.text_field :title, class: 'form-control' %><br>

            <%= f.label :isn %>
            <%= f.text_field :isn, class: 'form-control' %><br>

            <%= f.submit yield(:button_text), class: "btn btn-primary" %><br>
      <% end %>
            <button onclick="back();", class="btn-warning">Back</button>

Rails_Project/book_shelf/app/views/books/edit.html.erb
<% provide(:book, "Edit book") %>
<% provide(:button_text, 'Save changes')%>

<h1>Update your book</h1>

<div class="form-horizontal">
  <div class="form-group">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>

  </div>
</div>
  </div>

Rails_Project/book_shelf/app/views/books/index.html.erb
<p>Books information</p>
<p><%= link_to "User ", users_path %>
<table class="table-condensed">
	<thead>
		<tr>
			<th>Book name</th>
			<th>Author</th>
			<th>Title</th>
			<th>Isn</th>
			<th>Option</th>
		</tr>
	</thead>
	<tbody>
		<%= render partial: "book" , collection: @books %>
	</tbody>
</table>
<%= link_to 'previous', books_path(page: @page-1) %>

<% for i in 1..@allpage + 1 %>
<%= link_to i, books_path( page: i)%>
<% end %>

<%=  link_to 'next page', books_path(page: @page+1) %>

<%= link_to "New book", new_book_path  %></p>

Rails_Project/book_shelf/app/views/books/items.html.erb
<% @books.each do |book| %>

<div class="new-item">

	<ul >
		<li><a><%= link_to book.name, book_path(book) %></a></li>
		<li><a><%= link_to book.author, book_path(book) %></a></li>
		<li><a><%= link_to book.isn, book_path(book) %></a></li>
	</ul>

</div>

<% end %>

<%= link_to 'previous', root_path(page: @page-1) %>

<% for i in 1..@allpage %>
<%= link_to i, root_path( page: i)%>
<% end %>


<%=  link_to 'next page', root_path(page: @page+1) %>

Rails_Project/book_shelf/app/views/books/new.html.erb
<% provide(:book, "New book") %>
<% provide(:button_text, 'Create book')%>

<h1>Add a new book</h1>
<div class="form-horizontal">
  <div class="form-group">
  <div class="col-md-6 col-md-offset-3">
      <%= render 'form' %>
  </div>
</div>
</div>

Rails_Project/book_shelf/app/views/books/search.html.erb
<table class="table table-bordered">

	<thead>
		<tr>
			<th>Book name</th>
			<th>Author</th>
			<th>Title</th>
			<th>Isn</th>
			<th>Option</th>
		</tr>
	</thead>
	<tbody>
		<%= render partial: "book" , collection: @books %>
	</tbody>
</table>

Rails_Project/book_shelf/app/views/books/show.html.erb
<p>Book Information</p>
<p><%= link_to 'All Books', books_path%></p>
<div class="show">
  <p>Book Name: <%= link_to @book.name, book_path(@book) %></p>
  <p>Title: <%= @book.title %></p>
  <p>Author: <%= @book.author %></p>
  <p>Isn: <%= @book.isn %></p>

  <button onclick="back()" class="btn-warning">Back</button>

</div>