Rails_Project/book_shelf/config/routes.rb
# nodoc
Rails.application.routes.draw do
  # get 'password_resets/new'

  # get 'password_resets/edit'

  # get 'password_reset/new'

  # get 'password_reset/edit'

  # get 'resumes/index'
  # get 'resumes/new'
  # get 'password_resets/new'

  # get 'password_resets/edit'

  # get 'password_reset/new'

  # get 'password_reset/edit'

  # get 'resumes/create'
  # get 'resumes/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "users" => 'users#index'
  # get "users/new" => 'users#new'
  # get "users/:id" => 'users#show'
  # get "users/:id/edit" => 'users#edit'
  # post "users" => 'users#create'
  # put "users/:id" => 'users#update'
  # delete "users/:id" => 'users#destroy'
# 	collection do 
# 		get 'most_like'
# 	end
# 	resources :comments do
# 		resources :users
# 	end
# end
# resources :post do
#   collection do 
#     get 'most_like'
#   end
#   member do
#     get 'most_comment'
#   end
#   # resources :comments do
#   #   # resources :users
#   # end
# end

get "books/items"
get "books/search_book"
get "books/search"
get  '/register',  to: 'users#new'
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'
get '/signup' => 'users#new'
# get "login"

# resources :sessions, only: [:create, :new, :destroy]

root "books#items"
resources :users
resources :orders
resources :carts
resources :books
resources :account_activations, only: [:edit]
resources :password_resets, only: [:create, :new, :update, :edit]
end

Rails_Project/book_shelf/app/views/layouts/_foot.html.erb
<footer class="clr">
<div class="container">
  <div class="footinfo">
    <div class="about">
      <label>VỀ NHÀ SÁCH</label>
      <ul>
      <li><a href="#">GIỚI THIỆU CHUNG</a></li>
      <li><a href="#">NHÂN LỰC</a></li>
      <li><a href="#">TRANG THIẾT BỊ VÀ CƠ SỞ VẬT CHẤT</a></li>
      </ul>
    </div>
    <div class="supportlink">
      <label>HỖ TRỢ</label>
      <ul>
      <li><a href="#">TƯ VẤN VỀ SÁCH</a></li>
      <li><a href="#">SÁCH THƯỜNG THỨC </a></li>
      <li><a href="#">ĐẶT MUA SÁCH</a></li>
      </ul>
    </div>
  </div>
</div>
</footer>

Rails_Project/book_shelf/app/views/layouts/_head.html.erb
<body>
<header>
<div class="first">
  <div class="container">
    <div class="home">
    <%= image_tag 'logo.png'%>
      <h1>BOOKS STORE</h1>
      <h2>BOOKS for a fantastic life</h2>
    </div>
    <div class="support">
        </div>  
  </div>
</div>
<nav class="menu">
  <div class="container">
    <ul>
      <li><a href="/">TRANG CHỦ</a></li>
      <li><a href="#">GIỚI THIỆU</a></li>
      <li><p><%= link_to "QUẢN LÝ SÁCH", books_path %></p></a></li>
      <% if current_user %>
      <li><a><%= link_to 'GIỎ HÀNG', cart_path(current_user) %></a></li>
      <%end%>
      <li>
      <% if current_user %>
        <%= link_to current_user.name ,user_path(current_user)%> | <%= link_to "Logout", '/logout' %>
      <% else %>
        <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
      <% end %>
      </li>
    </ul>
    <div class="form-search">
      <form action="/books/search" method="get" accept-charset="utf-8">
        <input type="text" name="search_value" value="" class="form-control">
        <button class="btn-info" >Search</button>
        
      </form>
    </div>
  </div>  
</nav>
<div class="middle" >
    <div class="container">
      <span>
        <a href="/">TRANG CHỦ/</a>
        <a href="books">BOOK LIST</a>
      </span>
    </div>
</div>

Rails_Project/book_shelf/app/views/layouts/_leftsubmenu.html.erb
<div class="left-menu">
  <aside class="left-sidebar">
    <ul class="list-group">
      <li class="list-group-item"><%= link_to "New Book" , new_book_path %></li>
      <li class="list-group-item"><%= link_to "All Books" , books_path %></li>
      <li class="list-group-item"><%= link_to "All Users" , users_path %></li>
      <li class="list-group-item">
      <% if current_user %>
        <%= link_to "My orders", order_path(current_user) %>
      <% else %>
        <%= link_to 'Login', '/login' %> | <%= link_to 'Signup', '/signup' %>
      <% end %>
      </li>
    </ul>
  </aside>
</div>

Rails_Project/book_shelf/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Book Store</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <meta charset="utf-8">
  
</head>
<%= render 'layouts/head' %>
</header>
<main class="clr">

<div class="container">
<%= render 'layouts/leftsubmenu' %>
<div class="new-list">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>
	<%= yield %>	
</div>
</div>
</main>
<%= render 'layouts/foot' %>
</body>
</html>