Rails_Project/book_shelf/config/routes.rb
# nodoc
Rails.application.routes.draw do
  # get 'password_resets/new'

  # get 'password_resets/edit'

  # get 'password_reset/new'

  # get 'password_reset/edit'

  # get 'resumes/index'
  # get 'resumes/new'
  # get 'password_resets/new'

  # get 'password_resets/edit'

  # get 'password_reset/new'

  # get 'password_reset/edit'

  # get 'resumes/create'
  # get 'resumes/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get "users" => 'users#index'
  # get "users/new" => 'users#new'
  # get "users/:id" => 'users#show'
  # get "users/:id/edit" => 'users#edit'
  # post "users" => 'users#create'
  # put "users/:id" => 'users#update'
  # delete "users/:id" => 'users#destroy'
# 	collection do 
# 		get 'most_like'
# 	end
# 	resources :comments do
# 		resources :users
# 	end
# end
# resources :post do
#   collection do 
#     get 'most_like'
#   end
#   member do
#     get 'most_comment'
#   end
#   # resources :comments do
#   #   # resources :users
#   # end
# end

get "books/items"
get "books/search_book"
get "books/search"
get  '/register',  to: 'users#new'
get '/login' => 'sessions#new'
post '/login' => 'sessions#create'
get '/logout' => 'sessions#destroy'
get '/signup' => 'users#new'
# get "login"

# resources :sessions, only: [:create, :new, :destroy]

root "books#items"
resources :users
resources :orders
resources :carts
resources :books
resources :account_activations, only: [:edit]
resources :password_resets, only: [:create, :new, :update, :edit]
end

Rails_Project/book_shelf/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  birthday        :date
#  gender          :integer
#  password_digest :string(255)
#  user_name       :string(255)
#  avatar          :string(255)
#  provider        :string(255)
#  uid             :string(255)
#  role            :integer          default("member")
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# nothing
class User < ApplicationRecord
  attr_accessor :remember_token, :activation_token, :reset_token
  before_save :downcase_email
  before_create :create_activation_digest
  validates :name, presence: true, length: { minimum: 6, maximum: 30 }, on: :update
  validates :user_name, :email, uniqueness: true
  validates :user_name, :password, presence: true
  mount_uploader :avatar, ImageUploader
  enum role: %w[member mod admin]
  validates :avatar, file_size: { less_than: 5.megabytes }
  validates :uid, uniqueness: { scope: :provider }, on: :update
  validates :email, presence: true, if: proc { provider == 'email' }
  enum gender: %w[male female gay less other]
  has_secure_password
  has_many :carts
  has_one :cart
  has_many :orders, through: :carts
  has_many :comments

  # Activates an account.
  def activate
    # update_attribute(:activated, true)
    # update_attribute(:activated_at, Time.zone.now)
    update_columns(activated: true, activated_at: Time.zone.now)
  end

  # Sends activation email.
  def send_activation_email
    update_attribute(:activation_sent_at, Time.zone.now) if UserMailer.account_activation(self).deliver_now
  end

  # Returns true if the given token matches the digest.
  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def create_reset_digest
    self.reset_token = User.new_token
    # update_attribute(:reset_digest,  User.digest(reset_token))
    # update_attribute(:reset_sent_at, Time.zone.now)
    update_columns(reset_digest: User.digest(reset_token), reset_sent_at: Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end

  # NewToken
  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def password_reset_expired?
    reset_sent_at < 2.hours.ago
  end

  def activation_request_expired?
    activation_sent_at < 1.minutes.ago
  end

  def create_activation_digest
    self.activation_token = User.new_token
    self.activation_digest = User.digest(activation_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end

  private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    def remember
      self.remember_token = User.new_token
      update_attribute(:remember_digest, User.digest(remember_token))
    end
end

Rails_Project/book_shelf/app/controllers/users_controller.rb
# :nodoc:
class UsersController < ApplicationController
  include SessionsHelper
  before_filter :authorize, only: %i[destroy update edit]
  before_action :pagging, only: [:index]

  def pagging
    @allpage = User.all.count / 10
    @allpage = 1 if @allpage.zero?
    @page = params[:page].to_i
    @page = 1 if @page <= 0
    @page = @allpage if @page > @allpage
    @users = User.all.limit(10).offset((@page - 1) * 10)
  end

  def index
    # index method
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      @user.send_activation_email
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
    @user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :birthday, :gender, :password, :password_confirmation, :user_name, :avatar, :uid, :provider, :role)
    end
end

Rails_Project/book_shelf/app/helpers/users_helper.rb
# nodoc
module UsersHelper
end

Rails_Project/book_shelf/app/views/users/_form.html.erb
<% provide(:title, 'Sign up') %>

<p><%= link_to 'All Users', users_path %></p>
<%= form_for @user, html: { :multipart => true} do |f| %>
      <%  if  @user.errors.any?  %>
          <div  id="error_explanation">
              <h2>
                  <%= pluralize(@user.errors.count,  "error")  %>  prohibited
                  this  article from  being saved:
              </h2>
              <div class="alert alert-error">
                        <ul>
                        <%  @user.errors.full_messages.each  do  |msg| %>
                            <li><%= msg %></li>
                        <%  end %>
                    </ul>
                    </div>
          </div>
      <%  end %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %><br>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %><br>

      
      <%= f.label :birthday %>
      <%= f.date_field :birthday, class: 'form-control' %><br>

      <%= f.label :gender %>
      <%= f.select :gender, ['male','female','gay','less','other'], { :class => 'selectpicker'} %><br>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %><br>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.label 'user name' %>
      <%= f.text_field :user_name, class: 'form-control' %><br>

      <%= f.label :avatar %>
      <%= f.file_field :avatar, class: 'form-control' %><br>

      <%= f.label :thumb %>
      <%= image_tag f.object.avatar.thumb %><br>

      <%= f.label :uid %>
      <%= f.text_field :uid, class: 'form-control' %>

      <%= f.label :provider %>
      <%= f.select :provider, ['facebook','email','google +'] , { class: 'selectpicker' }%>


      <%= f.label :role %>
      <%= f.text_field :role, class: 'form-control' %>


      <%= f.submit yield(:button_text), onclick: 'validate()', class: "btn btn-primary" %><br>
<% end %>

      <button onclick="back();", class="btn-warning">Back</button>
<!-- <script>
  function validate(){
    var x = document.forms['new_user']["elements"]["user_email"].value;
    var y = document.forms['new_user']['user[provider]'].value;
    if (x== ''&& y == 'email'){
      alert('khong duoc de trong email');
      return window.location.reload();
    }
  }

</script>
 -->

Rails_Project/book_shelf/app/views/users/_user.html.erb
<tr>
	<td><%= user.email  %></td> 
	<td><%= user.user_name %></td>
	<td><%= image_tag user.avatar.thumb	 %></td>
	<td><%= user.role %></td>


	<td><%= link_to 'delete', user, :method => 'delete', data: {confirm: "are you sure that you want to delete user #{user.name}?"} %>/<%= link_to 'edit' , edit_user_path(user)  %>/<%= link_to 'show' , user_path(user)%></td>
</tr>
	

Rails_Project/book_shelf/app/views/users/edit.html.erb
<% provide(:user, "Edit user") %>
<% provide(:button_text, 'Save change')%>
<h1>Update your profile</h1>

<div class="form-group">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

Rails_Project/book_shelf/app/views/users/index.html.erb
<p>User</p>

<p><%= link_to 'Books' , books_path%></p>

<table class="table-condensed" >
<thead>
<tr>
	<th>Email</th>
	<th>UserName</th>
	<th>Avatar</th>
	<th>Role</th>
	<th>Option</th>
</tr>
</thead>
<tbody>
	<%= render partial: 'user', collection: @users %>
</tbody>
</table>

<%= link_to 'previous', users_path(page: @page-1) %>

	<% for i in 1..@allpage +1%>
			<%= link_to i, users_path( page: i)%>
<% end %>
<%=  link_to 'next page', users_path(page: @page+1) %>

<%= link_to 'New user' , new_user_path %>

Rails_Project/book_shelf/app/views/users/new.html.erb
<% provide(:user, 'Sign up') %>
<% provide(:button_text, 'Create account')%>
<h1>Update your profile</h1>

<div class="form-group">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

Rails_Project/book_shelf/app/views/users/show.html.erb
<p><%= link_to 'All Users', users_path%></p>
<p>User information: </p>
<p><%= link_to 'Edit your profile', edit_user_path(current_user)%></p>
<div class="show">
  <a><%= link_to image_tag(@user.avatar.thumb, :class => "img-circle",:alt => "Cinque Terre"), user_path(@user)  %></a>

  <p>User Name: <%= link_to @user.user_name, user_path(@user) %></p>
  <p>User Email : <%= @user.email %></p>
  <p>Birthday : <%= @user.birthday %></p>

  <button onclick="back()" class="btn-warning">Back</button>
</div>